remote:
  mqtt:
    clientid: 6599103899d8421398bcca388027a3df
    address: "ssl://sandbox.mqtt.iot.bj.baidubce.com:8884"
    username: e45c13c9d71c4ab5bf76448f01a52b3b/6599103899d8421398bcca388027a3df
    ca: var/db/openedge/cert/root.pem
    cert: var/db/openedge/cert/client.pem
    key: var/db/openedge/cert/client.key
  http:
    ca: var/db/openedge/cert/openapi.pem
    address: "https://iot-edge.baidu-int.com"
    insecure: true # shold be false online
logger:
  path: var/log/openedge/service.log
  level: debug
