hub:
  address: tcp://0.0.0.0:1883
  username: test
  password: hahaha
  keepalive: -1 # no ping/pong
rules:
#  - clientid: func-sql-filter-1
#    subscribe:
#      topic: t
#      qos: 1
#    function:
#      name: sql-filter
#    publish:
#      topic: t/sqlfilter
#      qos: 1
  - clientid: func-node8-sayhi-1
    subscribe:
      topic: t
    function:
      name: node8-sayhi
    publish:
      topic: t/node8hi
  - clientid: func-python3-sayhi-1
    subscribe:
      topic: t
    function:
      name: python3-sayhi
    publish:
      topic: t/py3hi
  - clientid: func-python2-sayhi-1
    subscribe:
      topic: t
    function:
      name: python2-sayhi
    publish:
      topic: t/py2hi
functions:
  # - name: sql-filter
  #   service: function-sql-filter
  - name: node8-sayhi
    service: function-node8-sayhi
  - name: python3-sayhi
    service: function-python3-sayhi
  - name: python2-sayhi
    service: function-python2-sayhi
    instance:
      min: 0
      max: 10
logger:
  path: var/log/baetyl/service.log
  level: "debug"
