hub:
  address: tcp://0.0.0.0:1883
  username: test
  password: hahaha
  clientid: timer-1
timer:
  interval: 30s
publish:
  topic: t
  payload:
    id: 1
logger:
  path: var/log/openedge/service.log
  level: "debug"
