version: V0
modules:
  - name: 'localhub'
    entry: 'hub.baidubce.com/openedge/openedge-hub:0.1.1'
    expose:
      - 1883:1883
  - name: 'localfunc'
    entry: 'hub.baiduce.com/openedge/openedge-function:0.1.1'
    resources:
      cpu:
        cpus: 1
      memory:
        limit: 500m
