version: v0
services:
  - name: localhub
    image: hub.baidubce.com/baetyl-beta/baetyl-hub
    replica: 1
    ports:
      - 1883:1883
      - 8883:8883
    mounts:
      - name: localhub-conf
        path: etc/baetyl
        readonly: true
      - name: localhub-cert
        path: var/db/baetyl/cert
        readonly: true
      - name: localhub-data
        path: var/db/baetyl/data
      - name: localhub-log
        path: var/log/baetyl
  # - name: agent
  #   image: hub.baidubce.com/baetyl-beta/baetyl-agent
  #   replica: 1
  #   mounts:
  #     - name: agent-conf
  #       path: etc/baetyl
  #       readonly: true
  #     - name: agent-cert
  #       path: var/db/baetyl/cert
  #       readonly: true
  #     - name: agent-volumes
  #       path: var/db/baetyl/volumes
  #     - name: agent-log
  #       path: var/log/baetyl
  #     - name: baetyl-log
  #       path: var/db/baetyl/baetyl-log/
  # - name: remote-iothub
  #   image: hub.baidubce.com/baetyl-beta/baetyl-remote-mqtt
  #   replica: 1
  #   mounts:
  #     - name: remote-iothub-conf
  #       path: etc/baetyl
  #       readonly: true
  #     - name: remote-iothub-cert
  #       path: var/db/baetyl/cert
  #       readonly: true
  #     - name: remote-iothub-log
  #       path: var/log/baetyl
  - name: function-manager
    image: hub.baidubce.com/baetyl-beta/baetyl-function-manager
    replica: 1
    mounts:
      - name: function-manager-conf
        path: etc/baetyl
        readonly: true
      - name: function-manager-log
        path: var/log/baetyl
  - name: function-python27-sayhi
    image: hub.baidubce.com/baetyl-beta/baetyl-function-python27
    replica: 0
    mounts:
      - name: function-sayhi-conf
        path: etc/baetyl
        readonly: true
      - name: function-sayhi-code
        path: var/db/baetyl/function-sayhi
        readonly: true
  - name: function-python36-sayhi
    image: hub.baidubce.com/baetyl-beta/baetyl-function-python36
    replica: 0
    mounts:
      - name: function-sayhi-conf
        path: etc/baetyl
        readonly: true
      - name: function-sayhi-code
        path: var/db/baetyl/function-sayhi
        readonly: true
  - name: function-node85-sayhi
    image: hub.baidubce.com/baetyl-beta/baetyl-function-node85
    replica: 0
    mounts:
      - name: function-sayjs-conf
        path: etc/baetyl
        readonly: true
      - name: function-sayjs-code
        path: var/db/baetyl/function-sayhi
        readonly: true
  - name: function-sql-filter
    image: hub.baidubce.com/baetyl-beta/baetyl-function-sql
    replica: 0
    mounts:
      - name: function-filter-conf
        path: etc/baetyl
        readonly: true
  - name: timer
    image: hub.baidubce.com/baetyl-beta/baetyl-timer
    replica: 1
    mounts:
      - name: timer-conf
        path: etc/baetyl
        readonly: true
  # - name: mosquitto
  #   image: eclipse-mosquitto
  #   replica: 1
  #   ports:
  #     - 1893:1893
  #   mounts:
  #     - name: mosquitto-config
  #       path: /mosquitto/config
  #       readonly: true
  #     - name: mosquitto-data
  #       path: /mosquitto/data
  #     - name: mosquitto-log
  #       path: /mosquitto/log

volumes:
  # hub
  - name: localhub-conf
    path: var/db/baetyl/localhub-conf
  - name: localhub-data
    path: var/db/baetyl/localhub-data
  - name: localhub-cert
    path: var/db/baetyl/localhub-cert-only-for-test
  - name: localhub-log
    path: var/db/baetyl/localhub-log
  # agent
  - name: agent-conf
    path: var/db/baetyl/agent-conf
  - name: agent-cert
    path: var/db/baetyl/agent-cert
  - name: agent-volumes
    path: var/db/baetyl
  - name: agent-log
    path: var/db/baetyl/agent-log
  - name: baetyl-log
    path: var/log/baetyl
  # remote mqtt
  - name: remote-iothub-conf
    path: var/db/baetyl/remote-iothub-conf
  - name: remote-iothub-cert
    path: var/db/baetyl/remote-iothub-cert
  - name: remote-iothub-log
    path: var/db/baetyl/remote-iothub-log
  # function
  - name: function-manager-conf
    path: var/db/baetyl/function-manager-conf
  - name: function-manager-log
    path: var/db/baetyl/function-manager-log
  - name: function-sayhi-conf
    path: var/db/baetyl/function-sayhi-conf
  - name: function-sayhi-code
    path: var/db/baetyl/function-sayhi-code
  - name: function-sayjs-conf
    path: var/db/baetyl/function-sayjs-conf
  - name: function-sayjs-code
    path: var/db/baetyl/function-sayjs-code
  - name: function-filter-conf
    path: var/db/baetyl/function-filter-conf
  # # mosquitto
  # - name: mosquitto-config
  #   path: var/db/baetyl/mosquitto-conf
  # - name: mosquitto-data
  #   path: var/db/baetyl/mosquitto-data
  # - name: mosquitto-log
  #   path: var/db/baetyl/mosquitto-log
  # timer
  - name: timer-conf
    path: var/db/baetyl/timer-conf
