name: image
on: push

jobs:
  image:
    name: docker build images of runtime
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: sudo apt update -y && sudo apt install -y qemu qemu-user-static
      - name: Install Docker CE for buildx
        run: |
          sudo apt update
          sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt update
          sudo apt install docker-ce
          docker -v
      - name: docker login
        run: |
          docker login -u ${{ secrets.DOCKER_REGISTRY_ID_INTERNAL }} -p ${{ secrets.DOCKER_REGISTRY_PASS_INTERNAL }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: build and publish baetyl-core image
        run: |
          make image PLATFORMS=all XFLAGS=--push REGISTRY=hub.baidubce.com/btl-test/
      - name: build and publish baetyl-init image
        run: |
          make init PLATFORMS=all XFLAGS=--push REGISTRY=hub.baidubce.com/btl-test/

